### IMPORTING LIBRARIES

In [3]:
import requests
import pandas as pd

### SENDING REQUEST TO BECHDEL API

In [4]:
# API URL = http://bechdeltest.com/?list=all
url = 'http://bechdeltest.com/api/v1/getMoviesByTitle?'
response=requests.get(url)
response

In [5]:
data= response.json()

### THE SHAPE OF OUR DATA

In [6]:
type(data)

list

In [7]:
data[0].keys()

dict_keys(['visible', 'date', 'submitterid', 'rating', 'dubious', 'imdbid', 'id', 'title', 'year'])

In [8]:
#There are 7,261 movies in the Bechdel database
movies= data
len(movies)

7292

In [9]:
#Create a df 
Bechdel_df= pd.DataFrame(movies)
Bechdel_df.head()

,date,dubious,id,imdbid,rating,submitterid,title,visible,year
0,2017-06-14 05:25:18,0,7685,2798920,3,14975,Annihilation,1,2018
1,2017-01-15 07:25:20,0,7397,5540622,2,14427,Alexander IRL,1,2017
2,2017-05-16 09:59:02,1,7607,2316204,2,14846,Alien: Covenant,1,2017
3,2017-07-03 19:57:33,0,7717,3890160,1,15029,Baby Driver,1,2017
4,2017-06-28 01:35:29,0,7707,5929750,3,15013,Beatriz at Dinner,1,2017

In [10]:
Bechdel_df.dtypes

date           object
dubious        object
id             object
imdbid         object
rating         object
submitterid    object
title          object
visible        object
year           object
dtype: object

In [11]:
Bechdel_df['imdb_int'] = Bechdel_df['imdbid']

In [12]:
Bechdel_df['rating'].value_counts()

3    4188
1    1612
0     756
2     736
Name: rating, dtype: int64

In [15]:
#READING IN BECHDEL SCORES FROM BECHDEL API BASED ON IMDB IDs
#REASON FOR MERGING ON IMDB ID - TITLES DID NOT MATCH PERFECTLY
#Consider the titles assigned to 'In the Mood For Love' and 'Mulholland Drive'
Bechdel_df[Bechdel_df['title'].str.contains("Mood")]

,date,dubious,id,imdbid,rating,submitterid,title,visible,year,imdb_int
4283,2012-05-08 04:43:39,0,3233,0118694,3,5147,Fa yeung nin wa (In the Mood for Love),1,2000,0118694

In [14]:
Bechdel_df[Bechdel_df['title'].str.contains("Mulholland")]

,date,dubious,id,imdbid,rating,submitterid,title,visible,year,imdb_int
4180,2009-12-18 00:19:01,0,568,0166924,3,293,Mulholland Dr.,1,2001,0166924

### IMPORTING IMDB IDS FROM CSV

In [69]:
df_imdb=pd.read_csv('imdb.csv')

In [128]:
df_imdb

                                                  name      url
0                                    12 Years a Slave   2024544
1                                                2046    212712
2                                24 Hour Party People    274309
3                                           25th Hour    307901
4                                              3-Iron    423866
5                                     35 Shots of Rum   1100048
6                          4 Months, 3 Weeks & 2 Days   1032846
7                                    5 Broken Cameras   2125423
8                                                 5x2    354356
9                                                 678   1764141
10                                          7 Letters   4691166
11                                           99 Homes   2891174
12                                A Borrowed Identity   2841572
13                                   A Commuters Life   6366476
14                   A Girl Walks Home Alone at Night   2326554
15                              A History of Violence    399146
16    A Pigeon Sat on a Branch Reflecting on Existe...  1883180
17                                          A Prophet   1235166
18                                       A Separation   1832382
19                                      A Serious Man   1019452
20                                       A Single Man   1315981
21                              A Tale of Two Sisters    365376
22                          A Time for Drunken Horses    259072
23                                     A Touch of Sin   2852400
24                           A Vinganca de Uma Mulher   2050453
25                        AI: Artificial Intelligence    212720
26                                         About Elly   1360860
27                                            Actress    102816
28                                         Adaptation    268126
29                                      Adventureland   1091722
..                                                 ...      ...
556                       Warming by the Devil's Fire   1065628
557                       We Need to Talk About Kevin   1242460
558                                           Weekend   1714210
559                                    Wendy and Lucy   1152850
560                            Werckmeister Harmonies    249241
561                           Wet Hot American Summer    243655
562                            What Time Is It There?    269746
563                                    When I Saw You   2369543
564     When the Levees Broke: A Requiem in Four Acts    783612
565                               Where Do We Go Now?   1772424
566                                          Whiplash   2582802
567                                    White Material   1135952
568                                              Wild   2305051
569                                        Wild Tales   3011894
570                                      Winter Sleep   2758880
571                                     Winter's Bone   1399683
572   Wolff Von Amerongen: Did He Commit Bankruptcy...   499138
573                                Woman on the Beach    835787
574                                 World of Tomorrow   4171032
575                                 Y Tu Mama Tambien    245574
576                            Yi Yi: A One and a Two    244316
577                                    Yossi & Jagger    334754
578                          You Aint Seen Nothin Yet   1690389
579                               You Can Count On Me    203230
580                            You Can Count on Me Me    203230
581                You Will Meet a Tall Dark Stranger   1182350
582                                   You, The Living    445336
583                                       Young Adult   1625346
584                                  Zero Dark Thirty   1790885
585                                            Zodiac    443706

[586 rows x 2 columns]

### JOINING DFS BASED ON IMDB IDS

In [77]:
#CHECKING THAT THE IMDB ID FOR MULHOLLAND DR MATCHES THE IMDB ID IN THE BECHDEL API
df_imdb[df_imdb['name'].str.contains("Mulholland")]

                   name     url
303   Mulholland Drive   166924

In [97]:
#Created a dictionary called records for imdbid and Bechdel ratings
my_list= Bechdel_df[['imdbid','rating']].to_dict('records')

In [98]:
my_list

[{'imdbid': '2798920', 'rating': '3'},
 {'imdbid': '5540622', 'rating': '2'},
 {'imdbid': '2316204', 'rating': '2'},
 {'imdbid': '2771200', 'rating': '3'},
 {'imdbid': '3874544', 'rating': '1'},
 {'imdbid': '4030600', 'rating': '3'},
 {'imdbid': '4287320', 'rating': '3'},
 {'imdbid': '5740806', 'rating': '3'},
 {'imdbid': '5834660', 'rating': '3'},
 {'imdbid': '5493706', 'rating': '3'},
 {'imdbid': '4144332', 'rating': '3'},
 {'imdbid': '5155780', 'rating': '3'},
 {'imdbid': '5001718', 'rating': '3'},
 {'imdbid': '4630562', 'rating': '3'},
 {'imdbid': '4465564', 'rating': '3'},
 {'imdbid': '4157510', 'rating': '3'},
 {'imdbid': '5052448', 'rating': '2'},
 {'imdbid': '1219827', 'rating': '3'},
 {'imdbid': '4481414', 'rating': '3'},
 {'imdbid': '3896198', 'rating': '3'},
 {'imdbid': '5710514', 'rating': '3'},
 {'imdbid': '5598192', 'rating': '3'},
 {'imdbid': '4425200', 'rating': '1'},
 {'imdbid': '1972591', 'rating': '1'},
 {'imdbid': '3731562', 'rating': '1'},
 {'imdbid': '4116284', 'rating': '3'},
 {'imdbid': '5442430', 'rating': '3'},
 {'imdbid': '3315342', 'rating': '3'},
 {'imdbid': '6264596', 'rating': '0'},
 {'imdbid': '4899370', 'rating': '3'},
 {'imdbid': '2345759', 'rating': '2'},
 {'imdbid': '4411596', 'rating': '3'},
 {'imdbid': '1790809', 'rating': '1'},
 {'imdbid': '3717490', 'rating': '3'},
 {'imdbid': '2334871', 'rating': '3'},
 {'imdbid': '3922818', 'rating': '3'},
 {'imdbid': '2763304', 'rating': '3'},
 {'imdbid': '1412528', 'rating': '3'},
 {'imdbid': '3462710', 'rating': '3'},
 {'imdbid': '1734493', 'rating': '3'},
 {'imdbid': '0451279', 'rating': '3'},
 {'imdbid': '1293847', 'rating': '3'},
 {'imdbid': '1179933', 'rating': '3'},
 {'imdbid': '3453052', 'rating': '3'},
 {'imdbid': '4172430', 'rating': '2'},
 {'imdbid': '4385888', 'rating': '3'},
 {'imdbid': '2304933', 'rating': '2'},
 {'imdbid': '4731136', 'rating': '1'},
 {'imdbid': '2112096', 'rating': '3'},
 {'imdbid': '2140479', 'rating': '2'},
 {'imdbid': '4456850', 'rating': '3'},
 {'imdbid': '2567026', 'rating': '3'},
 {'imdbid': '4247682', 'rating': '3'},
 {'imdbid': '4392770', 'rating': '3'},
 {'imdbid': '3721936', 'rating': '3'},
 {'imdbid': '2674430', 'rating': '0'},
 {'imdbid': '5221584', 'rating': '3'},
 {'imdbid': '2543164', 'rating': '3'},
 {'imdbid': '2094766', 'rating': '1'},
 {'imdbid': '4651520', 'rating': '3'},
 {'imdbid': '2261287', 'rating': '3'},
 {'imdbid': '3838728', 'rating': '3'},
 {'imdbid': '5974388', 'rating': '3'},
 {'imdbid': '2975590', 'rating': '2'},
 {'imdbid': None, 'rating': '3'},
 {'imdbid': '5973626', 'rating': '1'},
 {'imdbid': '4853102', 'rating': '1'},
 {'imdbid': '5512872', 'rating': '3'},
 {'imdbid': '3544218', 'rating': '1'},
 {'imdbid': '1082807', 'rating': '3'},
 {'imdbid': '5073620', 'rating': '3'},
 {'imdbid': '3691740', 'rating': '3'},
 {'imdbid': '4738360', 'rating': '1'},
 {'imdbid': '2702724', 'rating': '3'},
 {'imdbid': '3882082', 'rating': '3'},
 {'imdbid': '4869556', 'rating': '1'},
 {'imdbid': '1473832', 'rating': '3'},
 {'imdbid': '5700672', 'rating': '3'},
 {'imdbid': '4513674', 'rating': '1'},
 {'imdbid': '3498820', 'rating': '3'},
 {'imdbid': '3553976', 'rating': '3'},
 {'imdbid': '5294198', 'rating': '3'},
 {'imdbid': '1489889', 'rating': '2'},
 {'imdbid': '4468634', 'rating': '3'},
 {'imdbid': '4666726', 'rating': '3'},
 {'imdbid': '3065204', 'rating': '3'},
 {'imdbid': '4857264', 'rating': '3'},
 {'imdbid': '3014866', 'rating': '3'},
 {'imdbid': '2652118', 'rating': '3'},
 {'imdbid': '4104054', 'rating': '3'},
 {'imdbid': '5074352', 'rating': '2'},
 {'imdbid': '1431045', 'rating': '1'},
 {'imdbid': '2927212', 'rating': '3'},
 {'imdbid': '1860357', 'rating': '2'},
 {'imdbid': '5078204', 'rating': '3'},
 {'imdbid': '4645330', 'rating': '3'},
 {'imdbid': '5786040', 'rating': '3'},
 {'imdbid': '5348774', 'rating': '1'},
 {'imdbid': '5521550', 'rating': '3'},
 {'imdbid': '3410834', 'rating': '3'},
 {'imdbid': '4730986', 'rating': '3'},
 {'imdbid': '1211837', 'rating': '1'},
 {'imdbid': '4160708', 'rating': '3'},
 {'imdbid': '5526028', 'rating': '0'},
 {'imdbid': '2436682', 'rating': '1'},
 {'imdbid': '3882074', 'rating': '1'},
 {'imdbid': '1083452', 'rating': '2'},
 {'imdbid': '1878870', 'rating': '3'},
 {'imdbid': '3655972', 'rating': '3'},
 {'imdbid': '4644822', 'rating': '3'},
 {'imdbid': '3716530', 'rating': '3'},
 {'imdbid': '2093991', 'rating': '2'},
 {'imdbid': '3958780', 'rating': '3'},
 {'imdbid': '2937696', 'rating': '0'},
 {'imdbid': '5538078', 'rating': '3'},
 {'imdbid': '3183660', 'rating': '3'},
 {'imdbid': '2671706', 'rating': '3'},
 {'imdbid': '5595168', 'rating': '3'},
 {'imdbid': '2277860', 'rating': '3'},
 {'imdbid': '2025690', 'rating': '3'},
 {'imdbid': '4262174', 'rating': '3'},
 {'imdbid': '4136084', 'rating': '3'},
 {'imdbid': '3387542', 'rating': '3'},
 {'imdbid': '4158096', 'rating': '0'},
 {'imdbid': '1124037', 'rating': '2'},
 {'imdbid': '2452386', 'rating': '3'},
 {'imdbid': '1289401', 'rating': '3'},
 {'imdbid': '3631112', 'rating': '3'},
 {'imdbid': '2404233', 'rating': '2'},
 {'imdbid': '4667788', 'rating': '3'},
 {'imdbid': '4366830', 'rating': '3'},
 {'imdbid': '2034800', 'rating': '0'},
 {'imdbid': '2119532', 'rating': '1'},
 {'imdbid': '0475290', 'rating': '1'},
 {'imdbid': '5664684', 'rating': '3'},
 {'imdbid': '4016934', 'rating': '3'},
 {'imdbid': '3072482', 'rating': '1'},
 {'imdbid': '2582782', 'rating': '1'},
 {'imdbid': '4846340', 'rating': '3'},
 {'imdbid': '3451230', 'rating': '2'},
 {'imdbid': '1292566', 'rating': '3'},
 {'imdbid': '4698684', 'rating': '3'},
 {'imdbid': '2381991', 'rating': '3'},
 {'imdbid': '4007248', 'rating': '3'},
 {'imdbid': '5022702', 'rating': '3'},
 {'imdbid': '5168192', 'rating': '3'},
 {'imdbid': '3608930', 'rating': '2'},
 {'imdbid': '1628841', 'rating': '3'},
 {'imdbid': '3062096', 'rating': '2'},
 {'imdbid': '1355631', 'rating': '3'},
 {'imdbid': '4645368', 'rating': '3'},
 {'imdbid': '3393786', 'rating': '3'},
 {'imdbid': '1619029', 'rating': '3'},
 {'imdbid': '2140037', 'rating': '0'},
 {'imdbid': '4196776', 'rating': '1'},
 {'imdbid': '4326444', 'rating': '3'},
 {'imdbid': '3040964', 'rating': '1'},
 {'imdbid': '5091548', 'rating': '3'},
 {'imdbid': '4139124', 'rating': '3'},
 {'imdbid': '2667380', 'rating': '1'},
 {'imdbid': '5311514', 'rating': '3'},
 {'imdbid': '4551882', 'rating': '1'},
 {'imdbid': '4302938', 'rating': '1'},
 {'imdbid': '2267968', 'rating': '3'},
 {'imdbid': '3783958', 'rating': '3'},
 {'imdbid': '4621872', 'rating': '3'},
 {'imdbid': '0918940', 'rating': '0'},
 {'imdbid': '4370784', 'rating': '3'},
 {'imdbid': '5153952', 'rating': '3'},
 {'imdbid': '2547584', 'rating': '3'},
 {'imdbid': '4786282', 'rating': '3'},
 {'imdbid': '3741834', 'rating': '2'},
 {'imdbid': '5434870', 'rating': '3'},
 {'imdbid': '2361317', 'rating': '1'},
 {'imdbid': '1212428', 'rating': '1'},
 {'imdbid': '3068194', 'rating': '3'},
 {'imdbid': '3908142', 'rating': '3'},
 {'imdbid': '4669986', 'rating': '3'},
 {'imdbid': '2404435', 'rating': '0'},
 {'imdbid': '4034228', 'rating': '2'},
 {'imdbid': '3963816', 'rating': '1'},
 {'imdbid': '2674426', 'rating': '3'},
 {'imdbid': '2649554', 'rating': '1'},
 {'imdbid': '2823054', 'rating': '3'},
 {'imdbid': '1935859', 'rating': '3'},
 {'imdbid': '4540710', 'rating': '3'},
 {'imdbid': '3521164', 'rating': '3'},
 {'imdbid': '2241351', 'rating': '3'},
 {'imdbid': '3095734', 'rating': '0'},
 {'imdbid': '4975722', 'rating': '1'},
 {'imdbid': '4520364', 'rating': '3'},
 {'imdbid': '4824302', 'rating': '3'},
 {'imdbid': '4196848', 'rating': '3'},
 {'imdbid': '2091935', 'rating': '2'},
 {'imdbid': '5474644', 'rating': '3'},
 {'imdbid': '4438848', 'rating': '3'},
 {'imdbid': '1974419', 'rating': '3'},
 {'imdbid': '4698584', 'rating': '0'},
 {'imdbid': '3531824', 'rating': '3'},
 {'imdbid': '3799694', 'rating': '3'},
 {'imdbid': '4550098', 'rating': '3'},
 {'imdbid': '1594972', 'rating': '3'},
 {'imdbid': '3110958', 'rating': '1'},
 {'imdbid': '4158876', 'rating': '3'},
 {'imdbid': '4361050', 'rating': '3'},
 {'imdbid': '1355644', 'rating': '0'},
 {'imdbid': '5247022', 'rating': '1'},
 {'imdbid': '4714782', 'rating': '3'},
 {'imdbid': '2788732', 'rating': '3'},
 {'imdbid': '3960412', 'rating': '1'},
 {'imdbid': '1374989', 'rating': '3'},
 {'imdbid': '4094724', 'rating': '3'},
 {'imdbid': '4341582', 'rating': '3'},
 {'imdbid': '5274066', 'rating': '3'},
 {'imdbid': '2865120', 'rating': '3'},
 {'imdbid': '4954522', 'rating': '3'},
 {'imdbid': '3686998', 'rating': '3'},
 {'imdbid': '2592614', 'rating': '3'},
 {'imdbid': '2869728', 'rating': '0'},
 {'imdbid': '1267299', 'rating': '3'},
 {'imdbid': '3748528', 'rating': '3'},
 {'imdbid': '1700841', 'rating': '3'},
 {'imdbid': '2709768', 'rating': '2'},
 {'imdbid': '4052882', 'rating': '3'},
 {'imdbid': '4262980', 'rating': '1'},
 {'imdbid': '0490215', 'rating': '0'},
 {'imdbid': '3470600', 'rating': '3'},
 {'imdbid': '3544112', 'rating': '1'},
 {'imdbid': '3774114', 'rating': '1'},
 {'imdbid': '4258698', 'rating': '2'},
 {'imdbid': '5254640', 'rating': '3'},
 {'imdbid': '4972582', 'rating': '3'},
 {'imdbid': '2660888', 'rating': '1'},
 {'imdbid': '4624424', 'rating': '1'},
 {'imdbid': '1386697', 'rating': '3'},
 {'imdbid': '3263904', 'rating': '1'},
 {'imdbid': '4034354', 'rating': '2'},
 {'imdbid': '1639084', 'rating': '3'},
 {'imdbid': '3949660', 'rating': '3'},
 {'imdbid': '4120176', 'rating': '1'},
 {'imdbid': '4048272', 'rating': '3'},
 {'imdbid': '1712261', 'rating': '3'},
 {'imdbid': '1679335', 'rating': '3'},
 {'imdbid': '1542768', 'rating': '0'},
 {'imdbid': '4699388', 'rating': '3'},
 {'imdbid': '4273292', 'rating': '3'},
 {'imdbid': '3717252', 'rating': '2'},
 {'imdbid': '2938496', 'rating': '3'},
 {'imdbid': '5580664', 'rating': '3'},
 {'imdbid': '2005151', 'rating': '3'},
 {'imdbid': '0803096', 'rating': '3'},
 {'imdbid': '3553442', 'rating': '3'},
 {'imdbid': '4144190', 'rating': '1'},
 {'imdbid': '3385516', 'rating': '3'},
 {'imdbid': '4714568', 'rating': '3'},
 {'imdbid': '2948356', 'rating': '3'},
 {'imdbid': '2006295', 'rating': '3'},
 {'imdbid': '3391348', 'rating': '3'},
 {'imdbid': '3544082', 'rating': '1'},
 {'imdbid': '3685622', 'rating': '0'},
 {'imdbid': '4691166', 'rating': '3'},
 {'imdbid': '3953626', 'rating': '3'},
 {'imdbid': '2639254', 'rating': '3'},
 {'imdbid': '3577624', 'rating': '2'},
 {'imdbid': '1837562', 'rating': '3'},
 {'imdbid': '3303652', 'rating': '3'},
 {'imdbid': '3090670', 'rating': '3'},
 {'imdbid': '3717016', 'rating': '3'},
 {'imdbid': '2710826', 'rating': '3'},
 {'imdbid': '1655441', 'rating': '3'},
 {'imdbid': '3480446', 'rating': '2'},
 {'imdbid': '1243974', 'rating': '3'},
 {'imdbid': '3700804', 'rating': '2'},
 {'imdbid': '3316948', 'rating': '1'},
 {'imdbid': '2401878', 'rating': '2'},
 {'imdbid': '3368222', 'rating': '3'},
 {'imdbid': '3620762', 'rating': '3'},
 {'imdbid': '4069042', 'rating': '3'},
 {'imdbid': '0478970', 'rating': '2'},
 {'imdbid': '3727982', 'rating': '3'},
 {'imdbid': '2395427', 'rating': '3'},
 {'imdbid': '3422078', 'rating': '3'},
 {'imdbid': '2631186', 'rating': '1'},
 {'imdbid': '3856042', 'rating': '3'},
 {'imdbid': '1731701', 'rating': '3'},
 {'imdbid': '4437640', 'rating': '1'},
 {'imdbid': '4084744', 'rating': '3'},
 {'imdbid': '4714032', 'rating': '3'},
 {'imdbid': '3704352', 'rating': '3'},
 {'imdbid': '1596363', 'rating': '1'},
 {'imdbid': '2978576', 'rating': '2'},
 {'imdbid': '4195368', 'rating': '3'},
 {'imdbid': '1355683', 'rating': '1'},
 {'imdbid': '2717822', 'rating': '1'},
 {'imdbid': '3487994', 'rating': '2'},
 {'imdbid': '4899406', 'rating': '3'},
 {'imdbid': '4145324', 'rating': '3'},
 {'imdbid': '3682448', 'rating': '1'},
 {'imdbid': '3859304', 'rating': '3'},
 {'imdbid': '2381111', 'rating': '3'},
 {'imdbid': '3532278', 'rating': '0'},
 {'imdbid': '3707106', 'rating': '3'},
 {'imdbid': '3268668', 'rating': '3'},
 {'imdbid': '2402927', 'rating': '3'},
 {'imdbid': '4125300', 'rating': '3'},
 {'imdbid': '1823672', 'rating': '1'},
 {'imdbid': '4594834', 'rating': '3'},
 {'imdbid': '1014763', 'rating': '2'},
 {'imdbid': '1661199', 'rating': '3'},
 {'imdbid': '4005402', 'rating': '3'},
 {'imdbid': '4576612', 'rating': '1'},
 {'imdbid': '4515684', 'rating': '1'},
 {'imdbid': '3322364', 'rating': '1'},
 {'imdbid': '3076658', 'rating': '2'},
 {'imdbid': '2554274', 'rating': '3'},
 {'imdbid': '1528854', 'rating': '1'},
 {'imdbid': '0810819', 'rating': '3'},
 {'imdbid': '1172049', 'rating': '1'},
 {'imdbid': '3440298', 'rating': '3'},
 {'imdbid': '3172532', 'rating': '3'},
 {'imdbid': '4056738', 'rating': '3'},
 {'imdbid': '4767274', 'rating': '3'},
 {'imdbid': '3850214', 'rating': '1'},
 {'imdbid': '4265878', 'rating': '3'},
 {'imdbid': '3819668', 'rating': '1'},
 {'imdbid': '2910904', 'rating': '3'},
 {'imdbid': '1950135', 'rating': '2'},
 {'imdbid': '1666801', 'rating': '3'},
 {'imdbid': '2570858', 'rating': '3'},
 {'imdbid': '2109127', 'rating': '1'},
 {'imdbid': '3503460', 'rating': '1'},
 {'imdbid': '3416744', 'rating': '1'},
 {'imdbid': '1674771', 'rating': '2'},
 {'imdbid': '3289728', 'rating': '3'},
 {'imdbid': '2719848', 'rating': '2'},
 {'imdbid': '4291590', 'rating': '0'},
 {'imdbid': '0470752', 'rating': '1'},
 {'imdbid': '3726704', 'rating': '2'},
 {'imdbid': '2057392', 'rating': '3'},
 {'imdbid': '2097331', 'rating': '3'},
 {'imdbid': '1502712', 'rating': '0'},
 {'imdbid': '2935476', 'rating': '3'},
 {'imdbid': '2582502', 'rating': '3'},
 {'imdbid': '1658801', 'rating': '3'},
 {'imdbid': '2322441', 'rating': '3'},
 {'imdbid': '2118624', 'rating': '3'},
 {'imdbid': '2381941', 'rating': '1'},
 {'imdbid': '4026600', 'rating': '1'},
 {'imdbid': '3978720', 'rating': '1'},
 {'imdbid': '4216934', 'rating': '3'},
 {'imdbid': '3977462', 'rating': '3'},
 {'imdbid': '2820852', 'rating': '3'},
 {'imdbid': '2561572', 'rating': '1'},
 {'imdbid': '3711622', 'rating': '3'},
 {'imdbid': '1254322', 'rating': '3'},
 {'imdbid': '1979388', 'rating': '3'},
 {'imdbid': '1051904', 'rating': '2'},
 {'imdbid': '4270516', 'rating': '3'},
 {'imdbid': '2403021', 'rating': '3'},
 {'imdbid': '4062536', 'rating': '3'},
 {'imdbid': '2515034', 'rating': '1'},
 {'imdbid': '5105218', 'rating': '3'},
 {'imdbid': '3397918', 'rating': '3'},
 {'imdbid': '3460252', 'rating': '3'},
 {'imdbid': '3707396', 'rating': '3'},
 {'imdbid': '3766394', 'rating': '3'},
 {'imdbid': '2131532', 'rating': '3'},
 {'imdbid': '4472596', 'rating': '3'},
 {'imdbid': '2224026', 'rating': '3'},
 {'imdbid': '2510894', 'rating': '3'},
 {'imdbid': '3296658', 'rating': '1'},
 {'imdbid': '1951266', 'rating': '3'},
 {'imdbid': '3236120', 'rating': '3'},
 {'imdbid': '3278330', 'rating': '3'},
 {'imdbid': '1390411', 'rating': '1'},
 {'imdbid': '2096673', 'rating': '3'},
 {'imdbid': '3195644', 'rating': '3'},
 {'imdbid': '2908446', 'rating': '3'},
 {'imdbid': '2361509', 'rating': '3'},
 {'imdbid': '2625810', 'rating': '3'},
 {'imdbid': '4420110', 'rating': '3'},
 {'imdbid': '3715320', 'rating': '2'},
 {'imdbid': '4485178', 'rating': '3'},
 {'imdbid': '3614530', 'rating': '3'},
 {'imdbid': '2357547', 'rating': '3'},
 {'imdbid': '2446980', 'rating': '3'},
 {'imdbid': '1617661', 'rating': '3'},
 {'imdbid': '0369610', 'rating': '3'},
 {'imdbid': '3291148', 'rating': '1'},
 {'imdbid': '3878542', 'rating': '3'},
 {'imdbid': '3850590', 'rating': '3'},
 {'imdbid': '3472226', 'rating': '2'},
 {'imdbid': '4000768', 'rating': '3'},
 {'imdbid': '3715122', 'rating': '3'},
 {'imdbid': '4080768', 'rating': '3'},
 {'imdbid': '4428814', 'rating': '1'},
 {'imdbid': '4341864', 'rating': '2'},
 {'imdbid': '4392438', 'rating': '3'},
 {'imdbid': '3722070', 'rating': '3'},
 {'imdbid': '2493486', 'rating': '1'},
 {'imdbid': '1618442', 'rating': '3'},
 {'imdbid': '4060576', 'rating': '3'},
 {'imdbid': '2918436', 'rating': '3'},
 {'imdbid': '3569230', 'rating': '3'},
 {'imdbid': '4466872', 'rating': '3'},
 {'imdbid': '4319698', 'rating': '3'},
 {'imdbid': '1754656', 'rating': '3'},
 {'imdbid': '2210769', 'rating': '3'},
 {'imdbid': '3464902', 'rating': '3'},
 {'imdbid': '4108134', 'rating': '1'},
 {'imdbid': '2262345', 'rating': '1'},
 {'imdbid': '2726560', 'rating': '3'},
 {'imdbid': '2217859', 'rating': '1'},
 {'imdbid': '2279339', 'rating': '3'},
 {'imdbid': '2884018', 'rating': '1'},
 {'imdbid': '1392190', 'rating': '3'},
 {'imdbid': '2334733', 'rating': '2'},
 {'imdbid': '3877674', 'rating': '1'},
 {'imdbid': '3471098', 'rating': '3'},
 {'imdbid': '2268016', 'rating': '3'},
 {'imdbid': '1638355', 'rating': '3'},
 {'imdbid': '3064298', 'rating': '3'},
 {'imdbid': '0787524', 'rating': '0'},
 {'imdbid': '4428788', 'rating': '3'},
 {'imdbid': '3659388', 'rating': '3'},
 {'imdbid': '3369806', 'rating': '3'},
 {'imdbid': '4046784', 'rating': '3'},
 {'imdbid': '2582496', 'rating': '3'},
 {'imdbid': '3529656', 'rating': '3'},
 {'imdbid': '4501454', 'rating': '3'},
 {'imdbid': '0790770', 'rating': '0'},
 {'imdbid': '3817188', 'rating': '1'},
 {'imdbid': '4093680', 'rating': '3'},
 {'imdbid': '2293640', 'rating': '3'},
 {'imdbid': '2245003', 'rating': '3'},
 {'imdbid': '2381249', 'rating': '0'},
 {'imdbid': '2872462', 'rating': '3'},
 {'imdbid': '3045616', 'rating': '1'},
 {'imdbid': '3168230', 'rating': '1'},
 {'imdbid': '4498966', 'rating': '3'},
 {'imdbid': '3966404', 'rating': '3'},
 {'imdbid': '4450396', 'rating': '3'},
 {'imdbid': '3478232', 'rating': '3'},
 {'imdbid': '3833474', 'rating': '1'},
 {'imdbid': '4895704', 'rating': '3'},
 {'imdbid': '5005684', 'rating': '3'},
 {'imdbid': '4392726', 'rating': '3'},
 {'imdbid': '3756788', 'rating': '3'},
 {'imdbid': '3844362', 'rating': '3'},
 {'imdbid': '3332064', 'rating': '1'},
 {'imdbid': '3622592', 'rating': '2'},
 {'imdbid': '3043252', 'rating': '3'},
 {'imdbid': '1596345', 'rating': '1'},
 {'imdbid': '2452042', 'rating': '3'},
 {'imdbid': '3862750', 'rating': '2'},
 {'imdbid': '3430042', 'rating': '0'},
 {'imdbid': '2848292', 'rating': '3'},
 {'imdbid': '2120120', 'rating': '1'},
 {'imdbid': '2058673', 'rating': '0'},
 {'imdbid': '4171544', 'rating': '0'},
 {'imdbid': '6663788', 'rating': '3'},
 {'imdbid': '3742378', 'rating': '3'},
 {'imdbid': '3993894', 'rating': '3'},
 {'imdbid': '4780834', 'rating': '3'},
 {'imdbid': '1663202', 'rating': '0'},
 {'imdbid': '4439120', 'rating': '3'},
 {'imdbid': '3623726', 'rating': '3'},
 {'imdbid': '2479478', 'rating': '2'},
 {'imdbid': '3205394', 'rating': '1'},
 {'imdbid': '3170832', 'rating': '3'},
 {'imdbid': '2199571', 'rating': '1'},
 {'imdbid': '2126355', 'rating': '3'},
 {'imdbid': '3430416', 'rating': '2'},
 {'imdbid': '2555736', 'rating': '3'},
 {'imdbid': '2140379', 'rating': '1'},
 {'imdbid': '3661298', 'rating': '3'},
 {'imdbid': '2872750', 'rating': '0'},
 {'imdbid': '3397884', 'rating': '0'},
 {'imdbid': '3605262', 'rating': '3'},
 {'imdbid': '1850457', 'rating': '3'},
 {'imdbid': '2537390', 'rating': '3'},
 {'imdbid': '3205376', 'rating': '0'},
 {'imdbid': '1798684', 'rating': '2'},
 {'imdbid': '2379713', 'rating': '1'},
 {'imdbid': '2279373', 'rating': '2'},
 {'imdbid': '1895587', 'rating': '1'},
 {'imdbid': '3079380', 'rating': '3'},
 {'imdbid': '2488496', 'rating': '3'},
 {'imdbid': '2080374', 'rating': '3'},
 {'imdbid': '4858280', 'rating': '0'},
 {'imdbid': '1398426', 'rating': '1'},
 {'imdbid': '4191054', 'rating': '3'},
 {'imdbid': '3077214', 'rating': '3'},
 {'imdbid': '2994832', 'rating': '3'},
 {'imdbid': '2262161', 'rating': '3'},
 {'imdbid': '3247714', 'rating': '3'},
 {'imdbid': '4298958', 'rating': '3'},
 {'imdbid': '3824458', 'rating': '3'},
 {'imdbid': '4359416', 'rating': '3'},
 {'imdbid': '2637276', 'rating': '1'},
 {'imdbid': '3764966', 'rating': '3'},
 {'imdbid': '3757648', 'rating': '1'},
 {'imdbid': '1340138', 'rating': '0'},
 {'imdbid': '1441953', 'rating': '3'},
 {'imdbid': '3775086', 'rating': '1'},
 {'imdbid': '1870548', 'rating': '3'},
 {'imdbid': '4247740', 'rating': '3'},
 {'imdbid': '4010918', 'rating': '3'},
 {'imdbid': '2911674', 'rating': '3'},
 {'imdbid': '2461340', 'rating': '3'},
 {'imdbid': '4897214', 'rating': '3'},
 {'imdbid': '3019620', 'rating': '0'},

In [103]:
#Turn imdbid to an integer and return 111 if the movie didn't have an imdbid
for b in my_list:
    if b['imdbid'] is None:
        b['imdbid'] = 111
    b['id'] = int(b['imdbid'])

In [104]:
#Creating a new Bechdel df with imdbid integers
simple_Bechdel= pd.DataFrame(my_list)

In [105]:
simple_Bechdel

           id   imdbid rating
0     2798920  2798920      3
1     5540622  5540622      2
2     2316204  2316204      2
3     2771200  2771200      3
4     3874544  3874544      1
5     4030600  4030600      3
6     4287320  4287320      3
7     5740806  5740806      3
8     5834660  5834660      3
9     5493706  5493706      3
10    4144332  4144332      3
11    5155780  5155780      3
12    5001718  5001718      3
13    4630562  4630562      3
14    4465564  4465564      3
15    4157510  4157510      3
16    5052448  5052448      2
17    1219827  1219827      3
18    4481414  4481414      3
19    3896198  3896198      3
20    5710514  5710514      3
21    5598192  5598192      3
22    4425200  4425200      1
23    1972591  1972591      1
24    3731562  3731562      1
25    4116284  4116284      3
26    5442430  5442430      3
27    3315342  3315342      3
28    6264596  6264596      0
29    4899370  4899370      3
...       ...      ...    ...
7231   229024  0229024      0
7232      417  0000417      0
7233      413  0000413      0
7234   367177  0367177      0
7235   131934  0131934      0
7236      359  0000359      0
7237   258104  0258104      0
7238      272  0000272      0
7239   227438  0227438      0
7240      300  0000300      0
7241   257654  0257654      0
7242   377995  0377995      0
7243      304  0000304      0
7244      306  0000306      0
7245      313  0000313      0
7246   135453  0135453      0
7247   230746  0230746      0
7248   291476  0291476      0
7249      246  0000246      0
7250      230  0000230      3
7251      211  0000211      0
7252   135696  0135696      0
7253   224240  0224240      0
7254       12  0000012      0
7255       91  0000091      0
7256   223341  0223341      0
7257      131  0000131      0
7258   132134  0132134      0
7259       14  0000014      0
7260        3  0000003      0

[7261 rows x 3 columns]

In [106]:
#left merge of imdb df with bechdel df 
df_all=pd.merge(df_imdb,simple_Bechdel[['id','rating']], left_on='url', right_on='id', how='left')

In [107]:
#Not all movies have bechdel scores so we get some NaN values
df_all

,name,url,id,rating
0,12 Years a Slave,2024544,2024544.0,3
1,2046,212712,212712.0,3
2,24 Hour Party People,274309,274309.0,1
3,25th Hour,307901,307901.0,2
4,3-Iron,423866,423866.0,1
5,35 Shots of Rum,1100048,1100048.0,3
6,"4 Months, 3 Weeks & 2 Days",1032846,1032846.0,3
7,5 Broken Cameras,2125423,NaN,NaN
8,5x2,354356,NaN,NaN
9,678,1764141,1764141.0,3
10,7 Letters,4691166,4691166.0,3
11,99 Homes,2891174,NaN,NaN
12,A Borrowed Identity,2841572,NaN,NaN
13,A Commuters Life,6366476,NaN,NaN
14,A Girl Walks Home Alone at Night,2326554,2326554.0,3
15,A History of Violence,399146,399146.0,3
16,A Pigeon Sat on a Branch Reflecting on Existe...,1883180,1883180.0,1
17,A Prophet,1235166,1235166.0,1
18,A Separation,1832382,1832382.0,3
19,A Serious Man,1019452,1019452.0,2
20,A Single Man,1315981,1315981.0,1
21,A Tale of Two Sisters,365376,365376.0,3
22,A Time for Drunken Horses,259072,NaN,NaN
23,A Touch of Sin,2852400,NaN,NaN
24,A Vinganca de Uma Mulher,2050453,NaN,NaN
25,AI: Artificial Intelligence,212720,212720.0,1
26,About Elly,1360860,1360860.0,3
27,Actress,102816,NaN,NaN
28,Adaptation,268126,268126.0,3
29,Adventureland,1091722,1091722.0,3
...,...,...,...,...
556,Warming by the Devil's Fire,1065628,NaN,NaN
557,We Need to Talk About Kevin,1242460,1242460.0,3
558,Weekend,1714210,1714210.0,1
559,Wendy and Lucy,1152850,1152850.0,3
560,Werckmeister Harmonies,249241,NaN,NaN
561,Wet Hot American Summer,243655,243655.0,3
562,What Time Is It There?,269746,NaN,NaN
563,When I Saw You,2369543,NaN,NaN
564,When the Levees Broke: A Requiem in Four Acts,783612,NaN,NaN
565,Where Do We Go Now?,1772424,1772424.0,3
566,Whiplash,2582802,2582802.0,1
567,White Material,1135952,1135952.0,3
568,Wild,2305051,2305051.0,3
569,Wild Tales,3011894,3011894.0,3
570,Winter Sleep,2758880,NaN,NaN
571,Winter's Bone,1399683,1399683.0,3
572,Wolff Von Amerongen: Did He Commit Bankruptcy...,499138,NaN,NaN
573,Woman on the Beach,835787,NaN,NaN
574,World of Tomorrow,4171032,4171032.0,3
575,Y Tu Mama Tambien,245574,245574.0,0
576,Yi Yi: A One and a Two,244316,NaN,NaN
577,Yossi & Jagger,334754,334754.0,2
578,You Aint Seen Nothin Yet,1690389,NaN,NaN
579,You Can Count On Me,203230,NaN,NaN
580,You Can Count on Me Me,203230,NaN,NaN
581,You Will Meet a Tall Dark Stranger,1182350,1182350.0,3
582,"You, The Living",445336,NaN,NaN
583,Young Adult,1625346,1625346.0,3
584,Zero Dark Thirty,1790885,1790885.0,3
585,Zodiac,443706,443706.0,1

In [108]:
#Replace all NaN = None
df_all['rating'].fillna("None", inplace=True)

In [110]:
#Replace all NaN = None
df_all['id'].fillna("None", inplace=True)

In [111]:
df_all

,name,url,id,rating
0,12 Years a Slave,2024544,2.02454e+06,3
1,2046,212712,212712,3
2,24 Hour Party People,274309,274309,1
3,25th Hour,307901,307901,2
4,3-Iron,423866,423866,1
5,35 Shots of Rum,1100048,1.10005e+06,3
6,"4 Months, 3 Weeks & 2 Days",1032846,1.03285e+06,3
7,5 Broken Cameras,2125423,None,None
8,5x2,354356,None,None
9,678,1764141,1.76414e+06,3
10,7 Letters,4691166,4.69117e+06,3
11,99 Homes,2891174,None,None
12,A Borrowed Identity,2841572,None,None
13,A Commuters Life,6366476,None,None
14,A Girl Walks Home Alone at Night,2326554,2.32655e+06,3
15,A History of Violence,399146,399146,3
16,A Pigeon Sat on a Branch Reflecting on Existe...,1883180,1.88318e+06,1
17,A Prophet,1235166,1.23517e+06,1
18,A Separation,1832382,1.83238e+06,3
19,A Serious Man,1019452,1.01945e+06,2
20,A Single Man,1315981,1.31598e+06,1
21,A Tale of Two Sisters,365376,365376,3
22,A Time for Drunken Horses,259072,None,None
23,A Touch of Sin,2852400,None,None
24,A Vinganca de Uma Mulher,2050453,None,None
25,AI: Artificial Intelligence,212720,212720,1
26,About Elly,1360860,1.36086e+06,3
27,Actress,102816,None,None
28,Adaptation,268126,268126,3
29,Adventureland,1091722,1.09172e+06,3
...,...,...,...,...
556,Warming by the Devil's Fire,1065628,None,None
557,We Need to Talk About Kevin,1242460,1.24246e+06,3
558,Weekend,1714210,1.71421e+06,1
559,Wendy and Lucy,1152850,1.15285e+06,3
560,Werckmeister Harmonies,249241,None,None
561,Wet Hot American Summer,243655,243655,3
562,What Time Is It There?,269746,None,None
563,When I Saw You,2369543,None,None
564,When the Levees Broke: A Requiem in Four Acts,783612,None,None
565,Where Do We Go Now?,1772424,1.77242e+06,3
566,Whiplash,2582802,2.5828e+06,1
567,White Material,1135952,1.13595e+06,3
568,Wild,2305051,2.30505e+06,3
569,Wild Tales,3011894,3.01189e+06,3
570,Winter Sleep,2758880,None,None
571,Winter's Bone,1399683,1.39968e+06,3
572,Wolff Von Amerongen: Did He Commit Bankruptcy...,499138,None,None
573,Woman on the Beach,835787,None,None
574,World of Tomorrow,4171032,4.17103e+06,3
575,Y Tu Mama Tambien,245574,245574,0
576,Yi Yi: A One and a Two,244316,None,None
577,Yossi & Jagger,334754,334754,2
578,You Aint Seen Nothin Yet,1690389,None,None
579,You Can Count On Me,203230,None,None
580,You Can Count on Me Me,203230,None,None
581,You Will Meet a Tall Dark Stranger,1182350,1.18235e+06,3
582,"You, The Living",445336,None,None
583,Young Adult,1625346,1.62535e+06,3
584,Zero Dark Thirty,1790885,1.79088e+06,3
585,Zodiac,443706,443706,1

In [122]:
#drop duplicates
df_all.drop_duplicates(keep='first')

,name,url,id,rating
0,12 Years a Slave,2024544,2.02454e+06,3
1,2046,212712,212712,3
2,24 Hour Party People,274309,274309,1
3,25th Hour,307901,307901,2
4,3-Iron,423866,423866,1
5,35 Shots of Rum,1100048,1.10005e+06,3
6,"4 Months, 3 Weeks & 2 Days",1032846,1.03285e+06,3
7,5 Broken Cameras,2125423,None,None
8,5x2,354356,None,None
9,678,1764141,1.76414e+06,3
10,7 Letters,4691166,4.69117e+06,3
11,99 Homes,2891174,None,None
12,A Borrowed Identity,2841572,None,None
13,A Commuters Life,6366476,None,None
14,A Girl Walks Home Alone at Night,2326554,2.32655e+06,3
15,A History of Violence,399146,399146,3
16,A Pigeon Sat on a Branch Reflecting on Existe...,1883180,1.88318e+06,1
17,A Prophet,1235166,1.23517e+06,1
18,A Separation,1832382,1.83238e+06,3
19,A Serious Man,1019452,1.01945e+06,2
20,A Single Man,1315981,1.31598e+06,1
21,A Tale of Two Sisters,365376,365376,3
22,A Time for Drunken Horses,259072,None,None
23,A Touch of Sin,2852400,None,None
24,A Vinganca de Uma Mulher,2050453,None,None
25,AI: Artificial Intelligence,212720,212720,1
26,About Elly,1360860,1.36086e+06,3
27,Actress,102816,None,None
28,Adaptation,268126,268126,3
29,Adventureland,1091722,1.09172e+06,3
...,...,...,...,...
556,Warming by the Devil's Fire,1065628,None,None
557,We Need to Talk About Kevin,1242460,1.24246e+06,3
558,Weekend,1714210,1.71421e+06,1
559,Wendy and Lucy,1152850,1.15285e+06,3
560,Werckmeister Harmonies,249241,None,None
561,Wet Hot American Summer,243655,243655,3
562,What Time Is It There?,269746,None,None
563,When I Saw You,2369543,None,None
564,When the Levees Broke: A Requiem in Four Acts,783612,None,None
565,Where Do We Go Now?,1772424,1.77242e+06,3
566,Whiplash,2582802,2.5828e+06,1
567,White Material,1135952,1.13595e+06,3
568,Wild,2305051,2.30505e+06,3
569,Wild Tales,3011894,3.01189e+06,3
570,Winter Sleep,2758880,None,None
571,Winter's Bone,1399683,1.39968e+06,3
572,Wolff Von Amerongen: Did He Commit Bankruptcy...,499138,None,None
573,Woman on the Beach,835787,None,None
574,World of Tomorrow,4171032,4.17103e+06,3
575,Y Tu Mama Tambien,245574,245574,0
576,Yi Yi: A One and a Two,244316,None,None
577,Yossi & Jagger,334754,334754,2
578,You Aint Seen Nothin Yet,1690389,None,None
579,You Can Count On Me,203230,None,None
580,You Can Count on Me Me,203230,None,None
581,You Will Meet a Tall Dark Stranger,1182350,1.18235e+06,3
582,"You, The Living",445336,None,None
583,Young Adult,1625346,1.62535e+06,3
584,Zero Dark Thirty,1790885,1.79088e+06,3
585,Zodiac,443706,443706,1

In [123]:
df_all

,name,url,id,rating
0,12 Years a Slave,2024544,2.02454e+06,3
1,2046,212712,212712,3
2,24 Hour Party People,274309,274309,1
3,25th Hour,307901,307901,2
4,3-Iron,423866,423866,1
5,35 Shots of Rum,1100048,1.10005e+06,3
6,"4 Months, 3 Weeks & 2 Days",1032846,1.03285e+06,3
7,5 Broken Cameras,2125423,None,None
8,5x2,354356,None,None
9,678,1764141,1.76414e+06,3
10,7 Letters,4691166,4.69117e+06,3
11,99 Homes,2891174,None,None
12,A Borrowed Identity,2841572,None,None
13,A Commuters Life,6366476,None,None
14,A Girl Walks Home Alone at Night,2326554,2.32655e+06,3
15,A History of Violence,399146,399146,3
16,A Pigeon Sat on a Branch Reflecting on Existe...,1883180,1.88318e+06,1
17,A Prophet,1235166,1.23517e+06,1
18,A Separation,1832382,1.83238e+06,3
19,A Serious Man,1019452,1.01945e+06,2
20,A Single Man,1315981,1.31598e+06,1
21,A Tale of Two Sisters,365376,365376,3
22,A Time for Drunken Horses,259072,None,None
23,A Touch of Sin,2852400,None,None
24,A Vinganca de Uma Mulher,2050453,None,None
25,AI: Artificial Intelligence,212720,212720,1
26,About Elly,1360860,1.36086e+06,3
27,Actress,102816,None,None
28,Adaptation,268126,268126,3
29,Adventureland,1091722,1.09172e+06,3
...,...,...,...,...
556,Warming by the Devil's Fire,1065628,None,None
557,We Need to Talk About Kevin,1242460,1.24246e+06,3
558,Weekend,1714210,1.71421e+06,1
559,Wendy and Lucy,1152850,1.15285e+06,3
560,Werckmeister Harmonies,249241,None,None
561,Wet Hot American Summer,243655,243655,3
562,What Time Is It There?,269746,None,None
563,When I Saw You,2369543,None,None
564,When the Levees Broke: A Requiem in Four Acts,783612,None,None
565,Where Do We Go Now?,1772424,1.77242e+06,3
566,Whiplash,2582802,2.5828e+06,1
567,White Material,1135952,1.13595e+06,3
568,Wild,2305051,2.30505e+06,3
569,Wild Tales,3011894,3.01189e+06,3
570,Winter Sleep,2758880,None,None
571,Winter's Bone,1399683,1.39968e+06,3
572,Wolff Von Amerongen: Did He Commit Bankruptcy...,499138,None,None
573,Woman on the Beach,835787,None,None
574,World of Tomorrow,4171032,4.17103e+06,3
575,Y Tu Mama Tambien,245574,245574,0
576,Yi Yi: A One and a Two,244316,None,None
577,Yossi & Jagger,334754,334754,2
578,You Aint Seen Nothin Yet,1690389,None,None
579,You Can Count On Me,203230,None,None
580,You Can Count on Me Me,203230,None,None
581,You Will Meet a Tall Dark Stranger,1182350,1.18235e+06,3
582,"You, The Living",445336,None,None
583,Young Adult,1625346,1.62535e+06,3
584,Zero Dark Thirty,1790885,1.79088e+06,3
585,Zodiac,443706,443706,1

### INITIAL EXPLORATION OF THE BECHDEL SCORES

In [125]:
#45% of our critically acclaimed movies weren't in the bechdel database and didn't receive a score
#31% of our critically acclaimed movies passed the bechdel test and received a rating of 3
#24% of our critically acclaimed movies failed the bechdel test and received ratings of 0, 1, or 2
df_all['rating'].value_counts(normalize=True)

None    0.447099
3       0.310580
1       0.136519
2       0.061433
0       0.044369
Name: rating, dtype: float64

In [226]:
df_crits_dir = pd. read_csv ('critics-director.csv')

In [227]:
df_crits_dir.head()

,critic,crit_org,crit_country,movie,movie_year,director
0,Simon Abrams,Freelance film critic,US,Mulholland Drive,2001,David Lynch
1,Simon Abrams,Freelance film critic,US,In the Mood for Love,2000,Wong Kar-wai
2,Simon Abrams,Freelance film critic,US,The Tree of Life,2011,Terrence Malick
3,Simon Abrams,Freelance film critic,US,Yi Yi: A One and a Two,2000,Edward Yang
4,Simon Abrams,Freelance film critic,US,Goodbye to Language,2014,Jean-Luc Godard

In [228]:
df_all.head()

                     name      url           id rating
0       12 Years a Slave   2024544  2.02454e+06      3
1                   2046    212712       212712      3
2   24 Hour Party People    274309       274309      1
3              25th Hour    307901       307901      2
4                 3-Iron    423866       423866      1

In [229]:
#left merge df_crits_dir with with df_all
crits_dir_bechdel = pd.merge(df_crits_dir, df_all[['name','rating']], left_on='movie', right_on='name', how='left')

In [230]:
crits_dir_bechdel

,critic,crit_org,crit_country,movie,movie_year,director,name,rating
0,Simon Abrams,Freelance film critic,US,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
1,Simon Abrams,Freelance film critic,US,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
2,Simon Abrams,Freelance film critic,US,The Tree of Life,2011,Terrence Malick,The Tree of Life,0
3,Simon Abrams,Freelance film critic,US,Yi Yi: A One and a Two,2000,Edward Yang,Yi Yi: A One and a Two,None
4,Simon Abrams,Freelance film critic,US,Goodbye to Language,2014,Jean-Luc Godard,Goodbye to Language,None
5,Simon Abrams,Freelance film critic,US,The White Meadows,2009,Mohammad Rasoulof,The White Meadows,None
6,Simon Abrams,Freelance film critic,US,Night Across the Street,2012,Raoul Ruiz,Night Across the Street,None
7,Simon Abrams,Freelance film critic,US,Certified Copy,2010,Abbas Kiarostami,Certified Copy,3
8,Simon Abrams,Freelance film critic,US,Sparrow,2008,Johnnie To,Sparrow,0
9,Simon Abrams,Freelance film critic,US,Fados,2007,Carlos Saura,Fados,None
10,Sam Adams,Freelance film critic,US,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
11,Sam Adams,Freelance film critic,US,Eternal Sunshine of the Spotless Mind,2004,Michel Gondry,Eternal Sunshine of the Spotless Mind,2
12,Sam Adams,Freelance film critic,US,Syndromes and a Century,2006,Apichatpong Weerasethakul,Syndromes and a Century,None
13,Sam Adams,Freelance film critic,US,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
14,Sam Adams,Freelance film critic,US,The Act of Killing,2012,Joshua Oppenheimer,The Act of Killing,None
15,Sam Adams,Freelance film critic,US,The Grand Budapest Hotel,2014,Wes Anderson,The Grand Budapest Hotel,1
16,Sam Adams,Freelance film critic,US,The New World,2004,Terrence Malick,The New World,3
17,Sam Adams,Freelance film critic,US,Certified Copy,2010,Abbas Kiarostami,Certified Copy,3
18,Sam Adams,Freelance film critic,US,The World,2004,Jia Zhangke,The World,None
19,Sam Adams,Freelance film critic,US,Elephant,2003,Gus Van Sant,Elephant,3
20,Thelma Adams,Freelance film critic,US,Zero Dark Thirty,2012,Kathryn Bigelow,Zero Dark Thirty,3
21,Thelma Adams,Freelance film critic,US,A History of Violence,2005,David Cronenberg,A History of Violence,3
22,Thelma Adams,Freelance film critic,US,The Grand Budapest Hotel,2014,Wes Anderson,The Grand Budapest Hotel,1
23,Thelma Adams,Freelance film critic,US,Stories We Tell,2012,Sarah Polley,Stories We Tell,3
24,Thelma Adams,Freelance film critic,US,Casino Royale,2006,Martin Campbell,Casino Royale,1
25,Thelma Adams,Freelance film critic,US,Eternal Sunshine of the Spotless Mind,2004,Michel Gondry,Eternal Sunshine of the Spotless Mind,2
26,Thelma Adams,Freelance film critic,US,Tabu,2012,Miguel Gomes,Tabu,None
27,Thelma Adams,Freelance film critic,US,Snow White,2012,Pablo Berger,Snow White,3
28,Thelma Adams,Freelance film critic,US,Frozen River,2008,Courtney Hunt,Frozen River,3
29,Thelma Adams,Freelance film critic,US,Gosford Park,2001,Robert Altman,Gosford Park,3
...,...,...,...,...,...,...,...,...
3510,Stephanie Zacharek,Time Magazine,US,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
3511,Stephanie Zacharek,Time Magazine,US,Kings and Queen,2004,Arnaud Desplechin,Kings and Queen,None
3512,Stephanie Zacharek,Time Magazine,US,Yi Yi: A One and a Two,2000,Edward Yang,Yi Yi: A One and a Two,None
3513,Stephanie Zacharek,Time Magazine,US,Oldboy,2003,Park Chan-wook,Oldboy,1
3514,Stephanie Zacharek,Time Magazine,US,Antichrist,2009,Lars von Trier,Antichrist,0
3515,Stephanie Zacharek,Time Magazine,US,Children of Men,2006,Alfonso Cuarón,Children of Men,3
3516,Stephanie Zacharek,Time Magazine,US,Lost in Translation,2003,Sofia Coppola,Lost in Translation,3
3517,Stephanie Zacharek,Time Magazine,US,Femme Fatale,2002,Brian De Palma,Femme Fatale,None
3518,Stephanie Zacharek,Time Magazine,US,Casino Royale,2006,Martin Campbell,Casino Royale,1
3519,Stephanie Zacharek,Time Magazine,US,Blue Is the Warmest Color,2013,Abdellatif Kechiche,Blue Is the Warmest Color,3
3520,Chadi Zeneddine,Doha Film Institute,Qatar,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
3521,Chadi Zeneddine,Doha Film Institute,Qatar,The Tree of Life,2011,Terrence Malick,The Tree of Life,0
3522,Chadi Zeneddine,Doha Film Institute,Qatar,A Prophet,2009,Jacques Audiard,A Prophet,1
3523,Chadi Zeneddine,Doha Film Institute,Qatar,Amélie,2001,Jean-Pierre Jeunet,NaN,NaN
3524,Chadi Zeneddine,Doha Film Institute,Qatar,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
3525,Chadi Zeneddine,Doha Film Institute,Qatar,Brokeback Mountain,2005,Ang Lee,Brokeback Mountain,2
3526,Chadi Zeneddine,Doha Film Institute,Qatar,Talk to Her,2002,Pedro Almodóvar,Talk to Her,None
3527,Chadi Zeneddine,Doha Film Institute,Qatar,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
3528,Chadi Zeneddine,Doha Film Institute,Qatar,Eternal Sunshine of the Spotless Mind,2004,Michel Gondry,Eternal Sunshine of the Spotless Mind,2
3529,Chadi Zeneddine,Doha Film Institute,Qatar,Amour,2012,Michael Haneke,Amour,3
3530,Raymond Zhou,China Daily,China,"Spring, Summer, Fall, Winter…and Spring",2003,Kim Ki-duk,NaN,NaN
3531,Raymond Zhou,China Daily,China,The Hours,2002,Stephen Daldry,The Hours,3
3532,Raymond Zhou,China Daily,China,The Sun Also Rises,2007,Jiang Wen,The Sun Also Rises,None
3533,Raymond Zhou,China Daily,China,A Separation,2011,Asghar Farhadi,A Separation,3
3534,Raymond Zhou,China Daily,China,"Lust, Caution",2007,Ang Lee,"Lust, Caution",3
3535,Raymond Zhou,China Daily,China,The Lives of Others,2006,Florian Henckel von Donnersmarck,The Lives of Others,0
3536,Raymond Zhou,China Daily,China,Still Life,2006,Jia Zhangke,Still Life,None
3537,Raymond Zhou,China Daily,China,Birdman,2014,Alejandro González Iñárritu,Birdman,3
3538,Raymond Zhou,China Daily,China,Infernal Affairs,2002,Andrew Lau and Alan Mak,Infernal Affairs,1
3539,Raymond Zhou,China Daily,China,City of God,2002,Fernando Meirelles and Kátia Lund,City of God,1

In [231]:
crits_dir_bechdel.shape

(3540, 8)

In [232]:
crits_dir_bechdel['rating'].value_counts()

3       1488
None     900
1        552
0        240
2        220
Name: rating, dtype: int64

In [233]:
#The percentage of acclaimed movies from each country's critics passing the Bechdel test
crits_dir_bechdel.groupby('crit_country')['rating'].value_counts(normalize=True)

crit_country  rating
Argentina     3         0.550000
              None      0.300000
              1         0.100000
              2         0.050000
Australia     None      0.416667
              3         0.388889
              0         0.111111
              1         0.083333
Austria       None      0.555556
              3         0.222222
              0         0.111111
              1         0.111111
Bangladesh    3         0.444444
              1         0.222222
              None      0.222222
              2         0.111111
Belgium       3         0.500000
              None      0.400000
              1         0.100000
Brazil        3         0.700000
              0         0.100000
              1         0.100000
              2         0.100000
Canada        3         0.541667
              None      0.270833
              1         0.145833
              0         0.041667
Chile         3         0.450000
              1         0.250000
              2         0.150000
                          ...
South Africa  3         0.100000
South Korea   3         0.631579
              1         0.210526
              None      0.105263
              0         0.052632
Switzerland   3         0.666667
              None      0.222222
              1         0.111111
Taiwan        3         0.600000
              None      0.300000
              0         0.100000
Turkey        1         0.300000
              None      0.300000
              3         0.200000
              2         0.150000
              0         0.050000
UAE           3         0.633333
              1         0.166667
              None      0.166667
              2         0.033333
UK            3         0.473684
              None      0.216374
              1         0.134503
              0         0.116959
              2         0.058480
US            3         0.449875
              None      0.201754
              1         0.189223
              2         0.090226
              0         0.068922
Name: rating, Length: 145, dtype: float64

### CREATING A DATAFRAME WITH MOVIES THAT PASS THE BECHDEL TEST

In [238]:
#Creating a df with just the movies that passed the Bechdel test
pass_bechdel = crits_dir_bechdel[crits_dir_bechdel['rating'] == '3']

In [239]:
pass_bechdel

,critic,crit_org,crit_country,movie,movie_year,director,name,rating
0,Simon Abrams,Freelance film critic,US,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
1,Simon Abrams,Freelance film critic,US,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
7,Simon Abrams,Freelance film critic,US,Certified Copy,2010,Abbas Kiarostami,Certified Copy,3
10,Sam Adams,Freelance film critic,US,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
13,Sam Adams,Freelance film critic,US,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
16,Sam Adams,Freelance film critic,US,The New World,2004,Terrence Malick,The New World,3
17,Sam Adams,Freelance film critic,US,Certified Copy,2010,Abbas Kiarostami,Certified Copy,3
19,Sam Adams,Freelance film critic,US,Elephant,2003,Gus Van Sant,Elephant,3
20,Thelma Adams,Freelance film critic,US,Zero Dark Thirty,2012,Kathryn Bigelow,Zero Dark Thirty,3
21,Thelma Adams,Freelance film critic,US,A History of Violence,2005,David Cronenberg,A History of Violence,3
23,Thelma Adams,Freelance film critic,US,Stories We Tell,2012,Sarah Polley,Stories We Tell,3
27,Thelma Adams,Freelance film critic,US,Snow White,2012,Pablo Berger,Snow White,3
28,Thelma Adams,Freelance film critic,US,Frozen River,2008,Courtney Hunt,Frozen River,3
29,Thelma Adams,Freelance film critic,US,Gosford Park,2001,Robert Altman,Gosford Park,3
30,Arturo Aguilar,Rolling Stone Mexico,Mexico,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
31,Arturo Aguilar,Rolling Stone Mexico,Mexico,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
32,Arturo Aguilar,Rolling Stone Mexico,Mexico,Inception,2010,Christopher Nolan,Inception,3
33,Arturo Aguilar,Rolling Stone Mexico,Mexico,Pan's Labyrinth,2006,Guillermo Del Toro,Pan's Labyrinth,3
36,Arturo Aguilar,Rolling Stone Mexico,Mexico,"4 Months, 3 Weeks & 2 Days",2007,Cristian Mungiu,"4 Months, 3 Weeks & 2 Days",3
40,Matthew Anderson,BBC Culture,UK,The Piano Teacher,2001,Michael Haneke,The Piano Teacher,3
41,Matthew Anderson,BBC Culture,UK,Margaret,2011,Kenneth Lonergan,Margaret,3
43,Matthew Anderson,BBC Culture,UK,"4 Months, 3 Weeks & 2 Days",2007,Cristian Mungiu,"4 Months, 3 Weeks & 2 Days",3
45,Matthew Anderson,BBC Culture,UK,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
46,Matthew Anderson,BBC Culture,UK,Lourdes,2009,Jessica Hausner,Lourdes,3
47,Matthew Anderson,BBC Culture,UK,Red Road,2006,Andrea Arnold,Red Road,3
48,Matthew Anderson,BBC Culture,UK,Boyhood,2014,Richard Linklater,Boyhood,3
50,Tim Appelo,The Wrap,US,No Country For Old Men,2007,Joel and Ethan Coen,No Country For Old Men,3
51,Tim Appelo,The Wrap,US,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
52,Tim Appelo,The Wrap,US,A Separation,2011,Asghar Farhadi,A Separation,3
53,Tim Appelo,The Wrap,US,Pan's Labyrinth,2006,Guillermo Del Toro,Pan's Labyrinth,3
...,...,...,...,...,...,...,...,...
3469,Rahul Verma,Freelance film critic,UK,This Is England,2006,Shane Meadows,This Is England,3
3470,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
3472,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,A Separation,2011,Asghar Farhadi,A Separation,3
3473,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,Moulin Rouge!,2001,Baz Luhrmann,Moulin Rouge!,3
3475,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
3476,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
3477,Wen Tien-Hsiang,Taipei Golden Horse Film Festival,Taiwan,"4 Months, 3 Weeks & 2 Days",2007,Cristian Mungiu,"4 Months, 3 Weeks & 2 Days",3
3482,Stephen Whitty,Freelance film critic,US,Pan's Labyrinth,2006,Guillermo Del Toro,Pan's Labyrinth,3
3483,Stephen Whitty,Freelance film critic,US,The Skin I Live In,2011,Pedro Almodóvar,The Skin I Live In,3
3484,Stephen Whitty,Freelance film critic,US,Boyhood,2014,Richard Linklater,Boyhood,3
3486,Stephen Whitty,Freelance film critic,US,"4 Months, 3 Weeks & 2 Days",2007,Cristian Mungiu,"4 Months, 3 Weeks & 2 Days",3
3487,Stephen Whitty,Freelance film critic,US,A Separation,2011,Asghar Farhadi,A Separation,3
3488,Stephen Whitty,Freelance film critic,US,The Royal Tenenbaums,2001,Wes Anderson,The Royal Tenenbaums,3
3489,Stephen Whitty,Freelance film critic,US,No Country For Old Men,2007,Joel and Ethan Coen,No Country For Old Men,3
3490,Alissa Wilkinson,Christianity Today,US,No Country For Old Men,2007,Joel and Ethan Coen,No Country For Old Men,3
3497,Alissa Wilkinson,Christianity Today,US,Mad Max: Fury Road,2015,George Miller,Mad Max: Fury Road,3
3498,Alissa Wilkinson,Christianity Today,US,Selma,2014,Ava DuVernay,Selma,3
3503,Jake Wilson,Fairfax Media,Australia,The Deep Blue Sea,2011,Terence Davies,The Deep Blue Sea,3
3510,Stephanie Zacharek,Time Magazine,US,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
3515,Stephanie Zacharek,Time Magazine,US,Children of Men,2006,Alfonso Cuarón,Children of Men,3
3516,Stephanie Zacharek,Time Magazine,US,Lost in Translation,2003,Sofia Coppola,Lost in Translation,3
3519,Stephanie Zacharek,Time Magazine,US,Blue Is the Warmest Color,2013,Abdellatif Kechiche,Blue Is the Warmest Color,3
3520,Chadi Zeneddine,Doha Film Institute,Qatar,In the Mood for Love,2000,Wong Kar-wai,In the Mood for Love,3
3524,Chadi Zeneddine,Doha Film Institute,Qatar,Spirited Away,2001,Hayao Miyazaki,Spirited Away,3
3527,Chadi Zeneddine,Doha Film Institute,Qatar,Mulholland Drive,2001,David Lynch,Mulholland Drive,3
3529,Chadi Zeneddine,Doha Film Institute,Qatar,Amour,2012,Michael Haneke,Amour,3
3531,Raymond Zhou,China Daily,China,The Hours,2002,Stephen Daldry,The Hours,3
3533,Raymond Zhou,China Daily,China,A Separation,2011,Asghar Farhadi,A Separation,3
3534,Raymond Zhou,China Daily,China,"Lust, Caution",2007,Ang Lee,"Lust, Caution",3
3537,Raymond Zhou,China Daily,China,Birdman,2014,Alejandro González Iñárritu,Birdman,3

In [240]:
pass_bechdel.groupby('crit_country')['movie'].nunique()

crit_country
Argentina        10
Australia        13
Austria           4
Bangladesh        4
Belgium           5
Brazil            7
Canada           23
Chile             9
China             4
Colombia         13
Cuba             17
Egypt             2
France           12
Germany          20
Hong Kong         6
India            16
Indonesia         3
Israel           14
Italy            12
Kazakhstan        3
Lebanon           5
Mexico            8
Namibia           1
Philippines       2
Qatar             4
Senegal           5
Singapore        11
South Africa      1
South Korea       9
Switzerland       6
Taiwan            6
Turkey            3
UAE              17
UK               51
US              133
Name: movie, dtype: int64

### GEOJSON FILE FOR MOVIES THAT PASSED BECHDEL

In [241]:
df1 = pass_bechdel.groupby('crit_country')['movie'].value_counts().reset_index(name='count')
df1.head()

  crit_country                   movie  count
0    Argentina          Spirited Away       4
1    Argentina          Adventureland       2
2    Argentina                Boyhood       2
3    Argentina               Elephant       2
4    Argentina   In the Mood for Love       2

In [242]:
df1["string"] = df1["movie"] + ": " + df1["count"].map(str) + np.where(df1["count"]>1, ' votes', ' vote')
df1.head()

  crit_country                   movie  count                           string
0    Argentina          Spirited Away       4          Spirited Away : 4 votes
1    Argentina          Adventureland       2          Adventureland : 2 votes
2    Argentina                Boyhood       2                Boyhood : 2 votes
3    Argentina               Elephant       2               Elephant : 2 votes
4    Argentina   In the Mood for Love       2   In the Mood for Love : 2 votes

In [243]:
output = df1.groupby('crit_country')['string'].apply(lambda x: "<p>%s</p>" % '</p><p> '.join(x)).reset_index(name='article')
output.head()

  crit_country                                            article
0    Argentina  <p> Spirited Away : 4 votes</p><p>  Adventurel...
1    Australia  <p> A Separation : 4 votes</p><p>  Amour : 2 v...
2      Austria  <p> A History of Violence : 2 votes</p><p>  Ph...
3   Bangladesh  <p> A Separation : 2 votes</p><p>  Babel : 2 v...
4      Belgium  <p> Boyhood : 2 votes</p><p>  Ida : 2 votes</p...

In [244]:
crits = pass_bechdel.groupby('crit_country')['movie'].nunique().reset_index(name='headline')
crits.head()

  crit_country  headline
0    Argentina        10
1    Australia        13
2      Austria         4
3   Bangladesh         4
4      Belgium         5

In [245]:
output = output.merge(crits, how='left', on='crit_country')

In [246]:
output['lede'] = output['headline'].map(str) + " movie" + np.where(output["headline"]>1, 's', '')

In [247]:
output

,crit_country,article,headline,lede
0,Argentina,<p> Spirited Away : 4 votes</p><p> Adventurel...,10,10 movies
1,Australia,<p> A Separation : 4 votes</p><p> Amour : 2 v...,13,13 movies
2,Austria,<p> A History of Violence : 2 votes</p><p> Ph...,4,4 movies
3,Bangladesh,<p> A Separation : 2 votes</p><p> Babel : 2 v...,4,4 movies
4,Belgium,<p> Boyhood : 2 votes</p><p> Ida : 2 votes</p...,5,5 movies
5,Brazil,<p> Birdman : 2 votes</p><p> Children of Men ...,7,7 movies
6,Canada,<p> In the Mood for Love : 4 votes</p><p> Mar...,23,23 movies
7,Chile,<p> A History of Violence : 2 votes</p><p> Ch...,9,9 movies
8,China,<p> A Separation : 2 votes</p><p> Birdman : 2...,4,4 movies
9,Colombia,<p> A Separation : 6 votes</p><p> Pan's Labyr...,13,13 movies
10,Cuba,<p> In the Mood for Love : 6 votes</p><p> Mel...,17,17 movies
11,Egypt,<p> Boyhood : 2 votes</p><p> The Headless Wom...,2,2 movies
12,France,<p> Mulholland Drive : 8 votes</p><p> Amour :...,12,12 movies
13,Germany,<p> In the Mood for Love : 6 votes</p><p> Spi...,20,20 movies
14,Hong Kong,<p> 35 Shots of Rum : 2 votes</p><p> 4 Months...,6,6 movies
15,India,<p> In the Mood for Love : 6 votes</p><p> Inc...,16,16 movies
16,Indonesia,<p> A Separation : 2 votes</p><p> Spirited Aw...,3,3 movies
17,Israel,"<p> 4 Months, 3 Weeks & 2 Days : 4 votes</p><p...",14,14 movies
18,Italy,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",12,12 movies
19,Kazakhstan,<p> Boyhood : 2 votes</p><p> Only Lovers Left...,3,3 movies
20,Lebanon,<p> Blue Is the Warmest Color : 2 votes</p><p>...,5,5 movies
21,Mexico,<p> Mulholland Drive : 4 votes</p><p> 4 Month...,8,8 movies
22,Namibia,<p> 678 : 2 votes</p>,1,1 movie
23,Philippines,<p> Mulholland Drive : 2 votes</p><p> Spirite...,2,2 movies
24,Qatar,<p> Amour : 2 votes</p><p> In the Mood for Lo...,4,4 movies
25,Senegal,<p> A Separation : 2 votes</p><p> Birdman : 2...,5,5 movies
26,Singapore,<p> A Girl Walks Home Alone at Night : 2 votes...,11,11 movies
27,South Africa,<p> Fruitvale Station : 2 votes</p>,1,1 movie
28,South Korea,<p> Memories of Murder : 4 votes</p><p> Mulho...,9,9 movies
29,Switzerland,<p> A Separation : 2 votes</p><p> Boyhood : 2...,6,6 movies
30,Taiwan,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",6,6 movies
31,Turkey,<p> In the Mood for Love : 4 votes</p><p> Mul...,3,3 movies
32,UAE,<p> Mad Max: Fury Road : 4 votes</p><p> Pan's...,17,17 movies
33,UK,<p> 12 Years a Slave : 8 votes</p><p> Boyhood...,51,51 movies
34,US,<p> Mulholland Drive : 40 votes</p><p> In the...,133,133 movies

In [261]:
def value_to_color(val):
    if val < 15:
        return '#F64FFF'
    elif val < 30:
        return '#E013B4'
    elif val < 60:
        return '#B90F95'
    else:
        return '#930C76'

In [262]:
output['color'] = output['headline'].apply(lambda x: value_to_color(x))

In [263]:
output['crit_country']= output['crit_country'].str.replace('Hong Kong', 'China')

In [264]:
output

,crit_country,article,headline,lede,color
0,Argentina,<p> Spirited Away : 4 votes</p><p> Adventurel...,10,10 movies,#F64FFF
1,Australia,<p> A Separation : 4 votes</p><p> Amour : 2 v...,13,13 movies,#F64FFF
2,Austria,<p> A History of Violence : 2 votes</p><p> Ph...,4,4 movies,#F64FFF
3,Bangladesh,<p> A Separation : 2 votes</p><p> Babel : 2 v...,4,4 movies,#F64FFF
4,Belgium,<p> Boyhood : 2 votes</p><p> Ida : 2 votes</p...,5,5 movies,#F64FFF
5,Brazil,<p> Birdman : 2 votes</p><p> Children of Men ...,7,7 movies,#F64FFF
6,Canada,<p> In the Mood for Love : 4 votes</p><p> Mar...,23,23 movies,#E013B4
7,Chile,<p> A History of Violence : 2 votes</p><p> Ch...,9,9 movies,#F64FFF
8,China,<p> A Separation : 2 votes</p><p> Birdman : 2...,4,4 movies,#F64FFF
9,Colombia,<p> A Separation : 6 votes</p><p> Pan's Labyr...,13,13 movies,#F64FFF
10,Cuba,<p> In the Mood for Love : 6 votes</p><p> Mel...,17,17 movies,#E013B4
11,Egypt,<p> Boyhood : 2 votes</p><p> The Headless Wom...,2,2 movies,#F64FFF
12,France,<p> Mulholland Drive : 8 votes</p><p> Amour :...,12,12 movies,#F64FFF
13,Germany,<p> In the Mood for Love : 6 votes</p><p> Spi...,20,20 movies,#E013B4
14,China,<p> 35 Shots of Rum : 2 votes</p><p> 4 Months...,6,6 movies,#F64FFF
15,India,<p> In the Mood for Love : 6 votes</p><p> Inc...,16,16 movies,#E013B4
16,Indonesia,<p> A Separation : 2 votes</p><p> Spirited Aw...,3,3 movies,#F64FFF
17,Israel,"<p> 4 Months, 3 Weeks & 2 Days : 4 votes</p><p...",14,14 movies,#F64FFF
18,Italy,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",12,12 movies,#F64FFF
19,Kazakhstan,<p> Boyhood : 2 votes</p><p> Only Lovers Left...,3,3 movies,#F64FFF
20,Lebanon,<p> Blue Is the Warmest Color : 2 votes</p><p>...,5,5 movies,#F64FFF
21,Mexico,<p> Mulholland Drive : 4 votes</p><p> 4 Month...,8,8 movies,#F64FFF
22,Namibia,<p> 678 : 2 votes</p>,1,1 movie,#F64FFF
23,Philippines,<p> Mulholland Drive : 2 votes</p><p> Spirite...,2,2 movies,#F64FFF
24,Qatar,<p> Amour : 2 votes</p><p> In the Mood for Lo...,4,4 movies,#F64FFF
25,Senegal,<p> A Separation : 2 votes</p><p> Birdman : 2...,5,5 movies,#F64FFF
26,Singapore,<p> A Girl Walks Home Alone at Night : 2 votes...,11,11 movies,#F64FFF
27,South Africa,<p> Fruitvale Station : 2 votes</p>,1,1 movie,#F64FFF
28,South Korea,<p> Memories of Murder : 4 votes</p><p> Mulho...,9,9 movies,#F64FFF
29,Switzerland,<p> A Separation : 2 votes</p><p> Boyhood : 2...,6,6 movies,#F64FFF
30,Taiwan,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",6,6 movies,#F64FFF
31,Turkey,<p> In the Mood for Love : 4 votes</p><p> Mul...,3,3 movies,#F64FFF
32,UAE,<p> Mad Max: Fury Road : 4 votes</p><p> Pan's...,17,17 movies,#E013B4
33,UK,<p> 12 Years a Slave : 8 votes</p><p> Boyhood...,51,51 movies,#B90F95
34,US,<p> Mulholland Drive : 40 votes</p><p> In the...,133,133 movies,#930C76

In [265]:
import geopandas as gpd
geo_file = "/Users/EmyLiu/Downloads/Project/countries (1).geojson"
countries = gpd.read_file(geo_file)
countries

,geometry,id,name
0,POLYGON ((-59.42394239423942 13.15673092218655...,BRB,Barbados
1,(POLYGON ((-60.90009000900089 10.8402684910687...,TTO,Trinidad & Tobago
2,(POLYGON ((-61.76417641764176 17.1198353224122...,ATG,Antigua & Barbuda
3,(POLYGON ((-61.62016201620162 12.0403634855032...,GRD,Grenada
4,POLYGON ((41.53015301530155 -1.690955985701123...,SOM,Somalia
5,"POLYGON ((73.86138613861388 36.71208383620386,...",PAK,Pakistan
6,(POLYGON ((78.21782178217825 34.81425919384228...,IND,India
7,"POLYGON ((71.34113411341136 38.24708906164336,...",AFG,Afghanistan
8,(POLYGON ((16.93969396939696 -7.20302020432483...,AGO,Angola
9,"POLYGON ((19.7839783978398 42.46137613512276, ...",ALB,Albania
10,"POLYGON ((1.710171017101715 42.50323991399839,...",AND,Andorra
11,(POLYGON ((53.87938793879388 24.23667773126816...,ARE,United Arab Emirates
12,(POLYGON ((-68.64086408640864 -54.885864343659...,ARG,Argentina
13,"POLYGON ((46.13861386138615 38.86109115181918,...",ARM,Armenia
14,(POLYGON ((73.35733573357336 -53.0159488872151...,AUS,Australia
15,"POLYGON ((16.07560756075608 48.74094296646624,...",AUT,Austria
16,(POLYGON ((45.13051305130514 39.57277539270477...,AZE,Azerbaijan
17,POLYGON ((30.54905490549055 -2.402640226586719...,BDI,Burundi
18,"POLYGON ((5.022502250225017 51.47604318634029,...",BEL,Belgium
19,"POLYGON ((3.582358235823591 11.69149866153975,...",BEN,Benin
20,"POLYGON ((0.1620162016201618 14.4963718462065,...",BFA,Burkina Faso
21,(POLYGON ((91.93519351935197 21.71089640577222...,BGD,Bangladesh
22,"POLYGON ((23.49234923492349 43.88474461689395,...",BGR,Bulgaria
23,"POLYGON ((50.56705670567058 26.19032074546391,...",BHR,Bahrain
24,(POLYGON ((-73.03330333033303 21.1527126874305...,BHS,Bahamas
25,"POLYGON ((17.83978397839783 45.07088501836995,...",BIH,Bosnia and Herzegovina
26,"POLYGON ((28.60486048604861 56.09501345561738,...",BLR,Belarus
27,POLYGON ((-88.87488748874887 17.88733793513198...,BLZ,Belize
28,"POLYGON ((-65.004500450045 -11.98944558910442,...",BOL,Bolivia
29,(POLYGON ((-48.55085508550854 -27.813954004089...,BRA,Brazil
...,...,...,...
174,(POLYGON ((46.4986498649865 -9.742756122779312...,SYC,Seychelles
175,(POLYGON ((-176.2196219621962 -22.343753564341...,TON,Tonga
176,(POLYGON ((-171.5751575157516 -13.943088603300...,WSM,Samoa
177,(POLYGON ((-61.33213321332133 12.6962293545547...,VCT,Saint Vincent and the Grenadines
178,(POLYGON ((-62.55625562556256 17.1058807294536...,KNA,Saint Kitts and Nevis
179,(POLYGON ((174.6354635463546 -21.7018422882489...,FJI,Fiji
180,POLYGON ((-67.02070207020702 18.50134002530778...,PRI,Puerto Rico
181,(POLYGON ((-6.282628262826279 49.9131287749836...,GBR,United Kingdom
182,POLYGON ((-68.78487848784879 12.09618185733744...,CUW,Curaçao
183,"POLYGON ((77.06570657065708 35.10730564597164,...",KPA,"Kashmir, Pakistani administered"
184,"POLYGON ((79.36993699369935 33.16761722473443,...",KIA,"Kashmir, Indian administered"
185,"POLYGON ((33.46534653465346 35.00962349526185,...",CYN,Cyprus
186,"POLYGON ((77.7857785778578 35.49803424881078, ...",KAS,Siachen Glacier
187,"POLYGON ((21.40414041404142 42.85210473796192,...",KOS,Kosovo
188,"POLYGON ((9.486948694869483 47.06639181144132,...",LIE,Liechtenstein
189,"POLYGON ((33.89738973897391 9.500627567048795,...",SSD,South Sudan
190,"POLYGON ((121.6381638163816 25.22745383132457,...",TWN,Taiwan
191,(POLYGON ((-6.894689468946893 61.6349868601581...,FRO,Faroes
192,(POLYGON ((-59.71197119711971 -52.318219239288...,FLK,Falkland Islands
193,POLYGON ((-2.070207020702071 49.25726290593227...,GB1,Channel Islands
194,(POLYGON ((-72.31323132313231 21.8504423353576...,TCA,Turks and Caicos
195,POLYGON ((-4.590459045904595 54.08555206958746...,IMN,Isle of Man
196,POLYGON ((-8.694869486948676 25.99495644404432...,ESH,Western Sahara
197,POLYGON ((-52.36723672367236 3.151287770912624...,GUF,French Guiana
198,POLYGON ((-60.97209720972097 14.78941829833586...,MTQ,Martinique
199,POLYGON ((29.32493249324932 -29.08382196331721...,LSO,Lesotho
200,(POLYGON ((-61.62016201620162 16.2825597448997...,GLP,Guadeloupe
201,(POLYGON ((167.5427542754276 -22.5949362375956...,NCL,New Caledonia
202,(POLYGON ((-43.69036903690369 59.9046173332990...,GRL,Greenland
203,(POLYGON ((34.25742574257427 31.21397421053868...,PSE,Palestinian territories

In [266]:
countries['name']= countries['name'].str.replace('United Arab Emirates', 'UAE')
countries['name']= countries['name'].str.replace('United Kingdom', 'UK')
countries['name']= countries['name'].str.replace('USA', 'US')

In [267]:
output2 = pd.merge(output,countries[['name','geometry']],left_on='crit_country', right_on='name', how='left')

In [268]:
output2

,crit_country,article,headline,lede,color,name,geometry
0,Argentina,<p> Spirited Away : 4 votes</p><p> Adventurel...,10,10 movies,#F64FFF,Argentina,(POLYGON ((-68.64086408640864 -54.885864343659...
1,Australia,<p> A Separation : 4 votes</p><p> Amour : 2 v...,13,13 movies,#F64FFF,Australia,(POLYGON ((73.35733573357336 -53.0159488872151...
2,Austria,<p> A History of Violence : 2 votes</p><p> Ph...,4,4 movies,#F64FFF,Austria,"POLYGON ((16.07560756075608 48.74094296646624,..."
3,Bangladesh,<p> A Separation : 2 votes</p><p> Babel : 2 v...,4,4 movies,#F64FFF,Bangladesh,(POLYGON ((91.93519351935197 21.71089640577222...
4,Belgium,<p> Boyhood : 2 votes</p><p> Ida : 2 votes</p...,5,5 movies,#F64FFF,Belgium,"POLYGON ((5.022502250225017 51.47604318634029,..."
5,Brazil,<p> Birdman : 2 votes</p><p> Children of Men ...,7,7 movies,#F64FFF,Brazil,(POLYGON ((-48.55085508550854 -27.813954004089...
6,Canada,<p> In the Mood for Love : 4 votes</p><p> Mar...,23,23 movies,#E013B4,Canada,(POLYGON ((-66.76867686768676 44.7499293803234...
7,Chile,<p> A History of Violence : 2 votes</p><p> Ch...,9,9 movies,#F64FFF,Chile,(POLYGON ((-67.56075607560756 -55.806867478923...
8,China,<p> A Separation : 2 votes</p><p> Birdman : 2...,4,4 movies,#F64FFF,China,(POLYGON ((110.6930693069307 20.14798199441563...
9,Colombia,<p> A Separation : 6 votes</p><p> Pan's Labyr...,13,13 movies,#F64FFF,Colombia,(POLYGON ((-77.35373537353735 4.26765520759590...
10,Cuba,<p> In the Mood for Love : 6 votes</p><p> Mel...,17,17 movies,#E013B4,Cuba,(POLYGON ((-82.86228622862286 21.9341698931088...
11,Egypt,<p> Boyhood : 2 votes</p><p> The Headless Wom...,2,2 movies,#F64FFF,Egypt,(POLYGON ((33.10531053105311 31.24188339645576...
12,France,<p> Mulholland Drive : 8 votes</p><p> Amour :...,12,12 movies,#F64FFF,France,"(POLYGON ((9.45094509450945 42.68464962245942,..."
13,Germany,<p> In the Mood for Love : 6 votes</p><p> Spi...,20,20 movies,#E013B4,Germany,(POLYGON ((13.98739873987398 54.07159747662892...
14,China,<p> 35 Shots of Rum : 2 votes</p><p> 4 Months...,6,6 movies,#F64FFF,China,(POLYGON ((110.6930693069307 20.14798199441563...
15,India,<p> In the Mood for Love : 6 votes</p><p> Inc...,16,16 movies,#E013B4,India,(POLYGON ((78.21782178217825 34.81425919384228...
16,Indonesia,<p> A Separation : 2 votes</p><p> Spirited Aw...,3,3 movies,#F64FFF,Indonesia,(POLYGON ((123.3663366336634 -10.5660771073332...
17,Israel,"<p> 4 Months, 3 Weeks & 2 Days : 4 votes</p><p...",14,14 movies,#F64FFF,Israel,"POLYGON ((34.94149414941495 31.81402170775594,..."
18,Italy,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",12,12 movies,#F64FFF,Italy,(POLYGON ((15.64356435643566 38.26104365460191...
19,Kazakhstan,<p> Boyhood : 2 votes</p><p> Only Lovers Left...,3,3 movies,#F64FFF,Kazakhstan,(POLYGON ((50.02700270027003 44.93133908878454...
20,Lebanon,<p> Blue Is the Warmest Color : 2 votes</p><p>...,5,5 movies,#F64FFF,Lebanon,"POLYGON ((36.30963096309631 34.50725814875437,..."
21,Mexico,<p> Mulholland Drive : 4 votes</p><p> 4 Month...,8,8 movies,#F64FFF,Mexico,(POLYGON ((-110.9090909090909 18.7246135126444...
22,Namibia,<p> 678 : 2 votes</p>,1,1 movie,#F64FFF,Namibia,"POLYGON ((13.48334833483349 -17.0130990541792,..."
23,Philippines,<p> Mulholland Drive : 2 votes</p><p> Spirite...,2,2 movies,#F64FFF,Philippines,"(POLYGON ((119.8019801980198 5.06306700623275,..."
24,Qatar,<p> Amour : 2 votes</p><p> In the Mood for Lo...,4,4 movies,#F64FFF,Qatar,"POLYGON ((50.96309630963097 24.57158796227314,..."
25,Senegal,<p> A Separation : 2 votes</p><p> Birdman : 2...,5,5 movies,#F64FFF,Senegal,"POLYGON ((-14.4194419441944 16.65933375478036,..."
26,Singapore,<p> A Girl Walks Home Alone at Night : 2 votes...,11,11 movies,#F64FFF,Singapore,"POLYGON ((103.9603960396039 1.39300905813645, ..."
27,South Africa,<p> Fruitvale Station : 2 votes</p>,1,1 movie,#F64FFF,South Africa,(POLYGON ((37.85778577857786 -46.9457009502497...
28,South Korea,<p> Memories of Murder : 4 votes</p><p> Mulho...,9,9 movies,#F64FFF,South Korea,(POLYGON ((126.8226822682269 33.55834582757358...
29,Switzerland,<p> A Separation : 2 votes</p><p> Boyhood : 2...,6,6 movies,#F64FFF,Switzerland,"POLYGON ((9.666966696669675 47.45712041428047,..."
30,Taiwan,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",6,6 movies,#F64FFF,Taiwan,"POLYGON ((121.6381638163816 25.22745383132457,..."
31,Turkey,<p> In the Mood for Love : 4 votes</p><p> Mul...,3,3 movies,#F64FFF,Turkey,(POLYGON ((25.97659765976599 40.15886829696349...
32,UAE,<p> Mad Max: Fury Road : 4 votes</p><p> Pan's...,17,17 movies,#E013B4,UAE,(POLYGON ((53.87938793879388 24.23667773126816...
33,UK,<p> 12 Years a Slave : 8 votes</p><p> Boyhood...,51,51 movies,#B90F95,UK,(POLYGON ((-6.282628262826279 49.9131287749836...
34,US,<p> Mulholland Drive : 40 votes</p><p> In the...,133,133 movies,#930C76,US,(POLYGON ((144.8244824482449 13.44977737431591...

In [269]:
from geopandas import GeoDataFrame
geo_output = GeoDataFrame(output2)

In [270]:
geo_output

,crit_country,article,headline,lede,color,name,geometry
0,Argentina,<p> Spirited Away : 4 votes</p><p> Adventurel...,10,10 movies,#F64FFF,Argentina,(POLYGON ((-68.64086408640864 -54.885864343659...
1,Australia,<p> A Separation : 4 votes</p><p> Amour : 2 v...,13,13 movies,#F64FFF,Australia,(POLYGON ((73.35733573357336 -53.0159488872151...
2,Austria,<p> A History of Violence : 2 votes</p><p> Ph...,4,4 movies,#F64FFF,Austria,"POLYGON ((16.07560756075608 48.74094296646624,..."
3,Bangladesh,<p> A Separation : 2 votes</p><p> Babel : 2 v...,4,4 movies,#F64FFF,Bangladesh,(POLYGON ((91.93519351935197 21.71089640577222...
4,Belgium,<p> Boyhood : 2 votes</p><p> Ida : 2 votes</p...,5,5 movies,#F64FFF,Belgium,"POLYGON ((5.022502250225017 51.47604318634029,..."
5,Brazil,<p> Birdman : 2 votes</p><p> Children of Men ...,7,7 movies,#F64FFF,Brazil,(POLYGON ((-48.55085508550854 -27.813954004089...
6,Canada,<p> In the Mood for Love : 4 votes</p><p> Mar...,23,23 movies,#E013B4,Canada,(POLYGON ((-66.76867686768676 44.7499293803234...
7,Chile,<p> A History of Violence : 2 votes</p><p> Ch...,9,9 movies,#F64FFF,Chile,(POLYGON ((-67.56075607560756 -55.806867478923...
8,China,<p> A Separation : 2 votes</p><p> Birdman : 2...,4,4 movies,#F64FFF,China,(POLYGON ((110.6930693069307 20.14798199441563...
9,Colombia,<p> A Separation : 6 votes</p><p> Pan's Labyr...,13,13 movies,#F64FFF,Colombia,(POLYGON ((-77.35373537353735 4.26765520759590...
10,Cuba,<p> In the Mood for Love : 6 votes</p><p> Mel...,17,17 movies,#E013B4,Cuba,(POLYGON ((-82.86228622862286 21.9341698931088...
11,Egypt,<p> Boyhood : 2 votes</p><p> The Headless Wom...,2,2 movies,#F64FFF,Egypt,(POLYGON ((33.10531053105311 31.24188339645576...
12,France,<p> Mulholland Drive : 8 votes</p><p> Amour :...,12,12 movies,#F64FFF,France,"(POLYGON ((9.45094509450945 42.68464962245942,..."
13,Germany,<p> In the Mood for Love : 6 votes</p><p> Spi...,20,20 movies,#E013B4,Germany,(POLYGON ((13.98739873987398 54.07159747662892...
14,China,<p> 35 Shots of Rum : 2 votes</p><p> 4 Months...,6,6 movies,#F64FFF,China,(POLYGON ((110.6930693069307 20.14798199441563...
15,India,<p> In the Mood for Love : 6 votes</p><p> Inc...,16,16 movies,#E013B4,India,(POLYGON ((78.21782178217825 34.81425919384228...
16,Indonesia,<p> A Separation : 2 votes</p><p> Spirited Aw...,3,3 movies,#F64FFF,Indonesia,(POLYGON ((123.3663366336634 -10.5660771073332...
17,Israel,"<p> 4 Months, 3 Weeks & 2 Days : 4 votes</p><p...",14,14 movies,#F64FFF,Israel,"POLYGON ((34.94149414941495 31.81402170775594,..."
18,Italy,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",12,12 movies,#F64FFF,Italy,(POLYGON ((15.64356435643566 38.26104365460191...
19,Kazakhstan,<p> Boyhood : 2 votes</p><p> Only Lovers Left...,3,3 movies,#F64FFF,Kazakhstan,(POLYGON ((50.02700270027003 44.93133908878454...
20,Lebanon,<p> Blue Is the Warmest Color : 2 votes</p><p>...,5,5 movies,#F64FFF,Lebanon,"POLYGON ((36.30963096309631 34.50725814875437,..."
21,Mexico,<p> Mulholland Drive : 4 votes</p><p> 4 Month...,8,8 movies,#F64FFF,Mexico,(POLYGON ((-110.9090909090909 18.7246135126444...
22,Namibia,<p> 678 : 2 votes</p>,1,1 movie,#F64FFF,Namibia,"POLYGON ((13.48334833483349 -17.0130990541792,..."
23,Philippines,<p> Mulholland Drive : 2 votes</p><p> Spirite...,2,2 movies,#F64FFF,Philippines,"(POLYGON ((119.8019801980198 5.06306700623275,..."
24,Qatar,<p> Amour : 2 votes</p><p> In the Mood for Lo...,4,4 movies,#F64FFF,Qatar,"POLYGON ((50.96309630963097 24.57158796227314,..."
25,Senegal,<p> A Separation : 2 votes</p><p> Birdman : 2...,5,5 movies,#F64FFF,Senegal,"POLYGON ((-14.4194419441944 16.65933375478036,..."
26,Singapore,<p> A Girl Walks Home Alone at Night : 2 votes...,11,11 movies,#F64FFF,Singapore,"POLYGON ((103.9603960396039 1.39300905813645, ..."
27,South Africa,<p> Fruitvale Station : 2 votes</p>,1,1 movie,#F64FFF,South Africa,(POLYGON ((37.85778577857786 -46.9457009502497...
28,South Korea,<p> Memories of Murder : 4 votes</p><p> Mulho...,9,9 movies,#F64FFF,South Korea,(POLYGON ((126.8226822682269 33.55834582757358...
29,Switzerland,<p> A Separation : 2 votes</p><p> Boyhood : 2...,6,6 movies,#F64FFF,Switzerland,"POLYGON ((9.666966696669675 47.45712041428047,..."
30,Taiwan,"<p> 4 Months, 3 Weeks & 2 Days : 2 votes</p><p...",6,6 movies,#F64FFF,Taiwan,"POLYGON ((121.6381638163816 25.22745383132457,..."
31,Turkey,<p> In the Mood for Love : 4 votes</p><p> Mul...,3,3 movies,#F64FFF,Turkey,(POLYGON ((25.97659765976599 40.15886829696349...
32,UAE,<p> Mad Max: Fury Road : 4 votes</p><p> Pan's...,17,17 movies,#E013B4,UAE,(POLYGON ((53.87938793879388 24.23667773126816...
33,UK,<p> 12 Years a Slave : 8 votes</p><p> Boyhood...,51,51 movies,#B90F95,UK,(POLYGON ((-6.282628262826279 49.9131287749836...
34,US,<p> Mulholland Drive : 40 votes</p><p> In the...,133,133 movies,#930C76,US,(POLYGON ((144.8244824482449 13.44977737431591...

In [271]:
geo_output.to_file("bechdel_bbc_file.geojson", driver='GeoJSON')

In [272]:
df_all.to_csv("Bechdel_final.csv", index=False)